name: async_agent
channels:
  - defaults
  - conda-forge
dependencies:
  - pip:
      - promisio
      - openai
      - streamlit
      - aioconsole
      - pyee
      - textual
      - langchain==0.0.231
      - human-id
      - colorama
      - pydantic
      - python-dotenv
  - pip
