name: concurrent_agent_executor
channels:
  - defaults
  - conda-forge
dependencies:
  - pip:
      - streamlit
      - textual
      - aioconsole

      - openai
      - pyee
      - langchain==0.0.231
      - human-id
      - colorama
      - pydantic
      - python-dotenv
  - pip
